# Generated by Django 6.0.3 on 2026-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant_address',
            field=models.CharField(default='123 Developer Lane', max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant_name',
            field=models.CharField(default='RMS Local', max_length=100),
        ),
    ]
