# Generated by Django 6.0.3 on 2026-03-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem_rating_menuitem_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&q=80', max_length=600),
        ),
    ]
