# Generated by Django 6.0.3 on 2026-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menuitem_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cuisine',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
